package be.limero.socket;

public enum Field {
	INVALID, DST_DOMAIN, DST_DEVICE, DST_INSTANCE, DST_PROP, SRC_DOMAIN, SRC_DEVICE, SRC_INSTANCE, SRC_PROP, MESSAGE_ID, TYPE, // REQUEST,RESPONE,RECORD,RELEASE,COMPLETE,ACK
	QOS, ERRNO, PAYLOAD, DATA, TEXT, UART_PORT, UART_BAUDRATE, UART_MODE, TCP_HOST, TCP_PORT
}
